In [44]:
import pandas as pd

In [45]:
test_data = pd.read_csv('test_data.csv')
test_data.head()

   dlg_id  line_n     role                                               text
0       0       0   client                                               Алло
1       0       1  manager                                  Алло здравствуйте
2       0       2   client                                        Добрый день
3       0       3  manager  Меня зовут ангелина компания диджитал бизнес з...
4       0       4   client                                                Ага

In [46]:
greetings = ['здравствуйте', 'добрый день', 'доброе утро', 'добрый вечер']

In [47]:
%%timeit
test_data['greeting'] = False

for greeting in greetings:
    test_data['greeting'] |= test_data['text'].str.lower().str.contains(greeting)

7.98 ms ± 855 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [48]:
test_data[['greeting', "text"]][test_data.dlg_id == 4]
### пропущено приветствие в диалоге 4, реплика 304

     greeting                                               text
302     False                                               Алло
303     False                                               Алло
304     False                                             Добрый
305     False  Вот по виду платежи пообщаться помните мы вот ...
306     False                                                Угу
307     False                                   Ну в принципе да
308     False  Я понял ну мы хотели бы просто предложить тако...
309     False                                                Угу
310     False  Готовы будем для вашего клиента это использова...
311     False  Наверное в рамках недели полторы наверное займ...
312     False                            А на сколько можно идти
313     False  Понятно а оплата на сколько должна быть на это...
314     False                      Да мы на год принимаем оплату
315     False                                                Угу
316     False                                             Да так
317     False                                 Давайте я предложу
318     False  Хорошо и вы имеете ввиду доработку какую это к...
319     False  А вот а ну вот помните айдар вам не подходило ...
320     False     Там что как галочки просто вылезли да читались
321     False                                                Угу
322     False     Ну не только задача эти под под не запускается
323     False                 Ну вот вот вот им же главное чтобы
324     False  А я понял ну да да да тогда вот вот эти вот ве...
325     False  Клиентам уходило напоминание об очередном платеже
326     False                                                Угу
327     False                     Хорошо я дам ну да да обсудите
328     False             А в какой форме это вот ответ возьмите
329     False  А если про саму форму ну то есть вы получите т...
330     False                                       Если что угу
331     False                                             Ну вот
332     False  Хорошо я понял да у меня с ним связь будет в п...
333     False                                            Давайте
334     False  Все тогда а вас когда вам когда лучше тогда на...
335     False  Во вторник все ну с вами да тогда до вторника ...
336     False                                 Угу да до свидания

In [49]:
# Через регулярные выражения
# %%timeit
# test_data['greeting'] = test_data['text'].str.contains('|'.join(greetings))

In [50]:
# a. Извлекаем реплики с приветствием – где менеджер поздоровался:
filtered_test_data = test_data[test_data['greeting']]
filtered_test_data = filtered_test_data[filtered_test_data['role'] == 'manager']
#другой вариант:
#filtered_test_data = test_data[(test_data['greeting']) & (test_data['role'] == 'manager')]
filtered_test_data['text']

1             Алло здравствуйте
110           Алло здравствуйте
166           Алло здравствуйте
250    Алло дмитрий добрый день
Name: text, dtype: object

In [51]:
introduces = ['зовут', 'мое имя']

test_data['introduce'] = False

for introduce in introduces:
    test_data['introduce'] |= test_data['text'].str.lower().str.contains(introduce)
    
test_data

,dlg_id,line_n,role,text,greeting,introduce
0,0,0,client,Алло,False,False
1,0,1,manager,Алло здравствуйте,True,False
2,0,2,client,Добрый день,True,False
3,0,3,manager,Меня зовут ангелина компания диджитал бизнес з...,False,True
4,0,4,client,Ага,False,False
...,...,...,...,...,...,...
475,5,138,manager,По поводу виджетов и с ними уже обсудите конкр...,False,False
476,5,139,manager,Все я вам высылаю счет и с вами на связи если ...,False,False
477,5,140,client,Спасибо спасибо,False,False
478,5,141,client,Да да тогда созвонимся ага спасибо вам давайте,False,False
479,5,142,manager,Ну до свидания хорошего вечера,False,False

In [52]:
# b. Извлекаем реплики, где менеджер представил себя:

filtered_test_data = test_data[test_data['introduce']]
filtered_test_data = filtered_test_data[filtered_test_data['role'] == 'manager']
#другой вариант:
#filtered_test_data = test_data[(test_data['introduce']) & (test_data['role'] == 'manager')]
filtered_test_data['text']

3      Меня зовут ангелина компания диджитал бизнес з...
111    Меня зовут ангелина компания диджитал бизнес з...
167    Меня зовут ангелина компания диджитал бизнес з...
251    Добрый меня максим зовут компания китобизнес у...
Name: text, dtype: object

In [53]:
%pip install spacy

Requirement already satisfied: spacy in c:\users\f-i-n\anaconda3\lib\site-packages (3.4.1)
Requirement already satisfied: pathy>=0.3.5 in c:\users\f-i-n\anaconda3\lib\site-packages (from spacy) (0.6.2)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\f-i-n\anaconda3\lib\site-packages (from spacy) (3.0.7)
Requirement already satisfied: thinc<8.2.0,>=8.1.0 in c:\users\f-i-n\anaconda3\lib\site-packages (from spacy) (8.1.1)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\f-i-n\anaconda3\lib\site-packages (from spacy) (1.0.3)
Requirement already satisfied: wasabi<1.1.0,>=0.9.1 in c:\users\f-i-n\anaconda3\lib\site-packages (from spacy) (0.10.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\f-i-n\anaconda3\lib\site-packages (from spacy) (2.25.1)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\users\f-i-n\anaconda3\lib\site-packages (from spacy) (2.4.4)
Requirement already satisfied: numpy>=1.15.0 in c:\users\f-i-n\anaconda3\lib\site-packages (from spacy) (1.20.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\f-i-n\anaconda3\lib\site-packages (from spacy) (4.59.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.10.0,>=1.7.4 in c:\users\f-i-n\anaconda3\lib\site-packages (from spacy) (1.9.2)
Requirement already satisfied: jinja2 in c:\users\f-i-n\anaconda3\lib\site-packages (from spacy) (2.11.3)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\f-i-n\anaconda3\lib\site-packages (from spacy) (2.0.6)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.9 in c:\users\f-i-n\anaconda3\lib\site-packages (from spacy) (3.0.10)
Requirement already satisfied: typer<0.5.0,>=0.3.0 in c:\users\f-i-n\anaconda3\lib\site-packages (from spacy) (0.4.2)
Requirement already satisfied: packaging>=20.0 in c:\users\f-i-n\anaconda3\lib\site-packages (from spacy) (20.9)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in c:\users\f-i-n\anaconda3\lib\site-packages (from spacy) (3.3.0)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\f-i-n\anaconda3\lib\site-packages (from spacy) (2.0.8)
Requirement already satisfied: setuptools in c:\users\f-i-n\anaconda3\lib\site-packages (from spacy) (52.0.0.post20210125)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\f-i-n\anaconda3\lib\site-packages (from spacy) (1.0.8)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\f-i-n\anaconda3\lib\site-packages (from packaging>=20.0->spacy) (2.4.7)
Requirement already satisfied: smart-open<6.0.0,>=5.2.1 in c:\users\f-i-n\anaconda3\lib\site-packages (from pathy>=0.3.5->spacy) (5.2.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\f-i-n\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<1.10.0,>=1.7.4->spacy) (3.7.4.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\f-i-n\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2020.12.5)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\f-i-n\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\f-i-n\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (1.26.4)
Requirement already satisfied: idna<3,>=2.5 in c:\users\f-i-n\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.10)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\f-i-n\anaconda3\lib\site-packages (from thinc<8.2.0,>=8.1.0->spacy) (0.0.1)
Requirement already satisfied: blis<0.10.0,>=0.7.8 in c:\users\f-i-n\anaconda3\lib\site-packages (from thinc<8.2.0,>=8.1.0->spacy) (0.9.1)
Requirement already satisfied: click<9.0.0,>=7.1.1 in c:\users\f-i-n\anaconda3\lib\site-packages (from typer<0.5.0,>=0.3.0->spacy) (7.1.2)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\f-i-n\anaconda3\lib\site-packages (from jinja2->spacy) (1.1.1)
Note: you may need to restart the kernel to use updated packages.

In [54]:
from spacy.lang.ru import Russian

In [55]:
nlp = Russian()
doc = nlp("Съешь ещё этих мягких французских булок, анна, да выпей чаю.")

for token in doc:
    print(token.text, token.lemma_, token.pos_, token.is_stop)

Съешь   False
ещё   True
этих   True
мягких   False
французских   False
булок   False
,   False
анна   False
,   False
да   True
выпей   False
чаю   False
.   False

In [56]:
%%timeit
test_data['name'] = ''
docs = list(nlp.pipe(test_data['text']))
for i in range(len(docs)):
    for token in docs[i]:
        if token.pos_ == 'PROPN':
            test_data.loc[[i], ['name']] += token.text + ' '
test_data

11.8 ms ± 732 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [57]:
%%timeit
test_data['name'] = ''
for i in range(len(test_data)):
    if test_data['introduce'][i] == True:
        text = nlp(test_data['text'][i])
        for token in doc:
            if token.pos_ == 'PROPN':
                test_data.loc[[i], ['name']] += token.text + ' '

test_data

4.45 ms ± 558 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [58]:
# c. Извлекаем имя менеджера:
test_data[test_data['name'] != '']['name']

Series([], Name: name, dtype: object)

In [59]:
test_data['company'] = ''
for i in range(len(test_data)):
    if test_data['introduce'][i] == True:
        l = str(test_data.loc[[i], ['text']]).split()
        for j in range(len(l)):
            if l[j] == 'компания':
                test_data.loc[[i], ['company']] = l[j+1]
test_data

,dlg_id,line_n,role,text,greeting,introduce,name,company
0,0,0,client,Алло,False,False,,
1,0,1,manager,Алло здравствуйте,True,False,,
2,0,2,client,Добрый день,True,False,,
3,0,3,manager,Меня зовут ангелина компания диджитал бизнес з...,False,True,,диджитал
4,0,4,client,Ага,False,False,,
...,...,...,...,...,...,...,...,...
475,5,138,manager,По поводу виджетов и с ними уже обсудите конкр...,False,False,,
476,5,139,manager,Все я вам высылаю счет и с вами на связи если ...,False,False,,
477,5,140,client,Спасибо спасибо,False,False,,
478,5,141,client,Да да тогда созвонимся ага спасибо вам давайте,False,False,,
479,5,142,manager,Ну до свидания хорошего вечера,False,False,,

In [60]:
# d. Извлекаем название компании:
test_data[test_data['company'] != '']['company']

3        диджитал
111      диджитал
167      диджитал
251    китобизнес
Name: company, dtype: object

In [61]:
goodbye = ['до свидания','хорошего вечера', 'всего хорошего', 'хорошего дня', 'всего доброго']

test_data['bye'] = False

for bye in goodbye:
    test_data['bye'] |= test_data['text'].str.lower().str.contains(bye)
    
test_data

,dlg_id,line_n,role,text,greeting,introduce,name,company,bye
0,0,0,client,Алло,False,False,,,False
1,0,1,manager,Алло здравствуйте,True,False,,,False
2,0,2,client,Добрый день,True,False,,,False
3,0,3,manager,Меня зовут ангелина компания диджитал бизнес з...,False,True,,диджитал,False
4,0,4,client,Ага,False,False,,,False
...,...,...,...,...,...,...,...,...,...
475,5,138,manager,По поводу виджетов и с ними уже обсудите конкр...,False,False,,,False
476,5,139,manager,Все я вам высылаю счет и с вами на связи если ...,False,False,,,False
477,5,140,client,Спасибо спасибо,False,False,,,False
478,5,141,client,Да да тогда созвонимся ага спасибо вам давайте,False,False,,,False
479,5,142,manager,Ну до свидания хорошего вечера,False,False,,,True

In [62]:
# e. Извлекаем реплики, где менеджер попрощался:

filtered_test_data = test_data[test_data['bye']]
filtered_test_data = filtered_test_data[filtered_test_data['role'] == 'manager']
#другой вариант:
# filtered_test_data = test_data[(test_data['bye']) & (test_data['role'] == 'manager')]
filtered_test_data['text']

108                           Всего хорошего до свидания
162    Угу да вижу я эту почту хорошо тогда исправлю ...
163                                          До свидания
300    Угу все хорошо да понедельника тогда всего доб...
335    Во вторник все ну с вами да тогда до вторника ...
479                       Ну до свидания хорошего вечера
Name: text, dtype: object

In [63]:
# f. Проверяем требование к менеджеру: «В каждом диалоге обязательно необходимо поздороваться и попрощаться с клиентом»
df2 = test_data[test_data['role'] == 'manager'][['dlg_id', 'greeting', 'bye']]
df2 = df2.groupby('dlg_id').agg({'greeting': 'max', 'bye': 'max'})
df2['fulfillment'] = df2['greeting'] & df2['bye']
df2
# Таким образом, видим, что требование выполняется в диалогах 0, 1 и 3.

        greeting    bye  fulfillment
dlg_id
0           True   True         True
1           True   True         True
2           True  False        False
3           True   True         True
4          False   True        False
5          False   True        False